# Generated by Django 5.2.7 on 2025-10-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='is_delivery_man',
        ),
    ]
