# Generated by Django 5.2.7 on 2025-10-23 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_imageproduct_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1500)]),
        ),
    ]
