# Generated by Django 5.2.7 on 2025-10-24 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproduct',
            name='main',
        ),
    ]
