# Generated by Django 5.2.7 on 2025-10-26 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_productcart_updated_at_alter_cart_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcart',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_product', to='cart.cart'),
        ),
    ]
