# Generated by Django 5.2.7 on 2025-10-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='product_id',
            field=models.IntegerField(unique=True),
        ),
    ]
