# Generated by Django 5.2.7 on 2025-10-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_trackingstatus_order_delivery_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trakingevent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
