# Generated by Django 5.2.7 on 2025-10-28 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_payment_methods_order_payment_method'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrakingEvent',
            new_name='TrackingEvent',
        ),
    ]
