# Generated by Django 5.2.7 on 2025-10-16 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=30)),
                ('payment_methods', models.ManyToManyField(to='orders.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.IntegerField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='product_order', to='orders.order')),
            ],
        ),
    ]
