# Generated by Django 5.2.7 on 2025-10-26 01:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_order', to='orders.order'),
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=50)),
                ('estimated_delivery', models.DateField()),
                ('delivered', models.BooleanField(default=False)),
                ('receiver', models.CharField(blank=True, max_length=150, null=True)),
                ('traking_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order_shipping', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='TrakingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_traking', to='orders.shipping')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_tracking', to='orders.trackingstatus')),
            ],
        ),
        migrations.AddIndex(
            model_name='shipping',
            index=models.Index(fields=['traking_code'], name='orders_ship_traking_c7196c_idx'),
        ),
        migrations.AddIndex(
            model_name='shipping',
            index=models.Index(fields=['address'], name='orders_ship_address_fffbdd_idx'),
        ),
    ]
