# Generated by Django 5.2.7 on 2025-10-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_timestamp_alter_trakingevent_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='description',
        ),
        migrations.AddField(
            model_name='shipping',
            name='delivered_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingstatus',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
