# Generated by Django 5.2.7 on 2025-10-27 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_shipping_description_shipping_delivered_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_methods',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payment_method_order', to='orders.paymentmethod'),
            preserve_default=False,
        ),
    ]
