# Generated by Django 5.2.7 on 2025-10-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
